language: ruby

rvm:
- 2.0.0
- 1.9.3
- 1.9.2
- ruby-head

env:
  - RUBYGEMS_VERSION=2.0.3 CHEF_VERSION=11.8.0
  - RUBYGEMS_VERSION=2.0.3 CHEF_VERSION=10.28.2
  - RUBYGEMS_VERSION=1.8.25 CHEF_VERSION=11.8.0
  - RUBYGEMS_VERSION=1.8.25 CHEF_VERSION=10.28.2

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version

bundler_args: --without guard

matrix:
  exclude:
  - rvm: 2.0.0
    env: RUBYGEMS_VERSION=1.8.25 CHEF_VERSION=10.28.2
  - rvm: 2.0.0
    env: RUBYGEMS_VERSION=1.8.25 CHEF_VERSION=11.8.0
  allow_failures:
  - rvm: ruby-head
